#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Lingua-EN-Inflect-Number
Version  : 1.12
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Lingua-EN-Inflect-Number-1.12.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Lingua-EN-Inflect-Number-1.12.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libl/liblingua-en-inflect-number-perl/liblingua-en-inflect-number-perl_1.12-1.debian.tar.xz
Summary  : 'Force number of words to singular or plural'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Lingua-EN-Inflect-Number-license
Requires: perl-Lingua-EN-Inflect-Number-man
Requires: perl(Lingua::EN::Inflect)
BuildRequires : perl(Lingua::EN::Inflect)

%description
This archive contains the distribution Lingua-EN-Inflect-Number,
version 1.12:
Force number of words to singular or plural

%package license
Summary: license components for the perl-Lingua-EN-Inflect-Number package.
Group: Default

%description license
license components for the perl-Lingua-EN-Inflect-Number package.


%package man
Summary: man components for the perl-Lingua-EN-Inflect-Number package.
Group: Default

%description man
man components for the perl-Lingua-EN-Inflect-Number package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Lingua-EN-Inflect-Number-1.12
mkdir -p %{_topdir}/BUILD/Lingua-EN-Inflect-Number-1.12/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Lingua-EN-Inflect-Number-1.12/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Lingua-EN-Inflect-Number
cp LICENSE %{buildroot}/usr/share/doc/perl-Lingua-EN-Inflect-Number/LICENSE
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Lingua-EN-Inflect-Number/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Lingua/EN/Inflect/Number.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Lingua-EN-Inflect-Number/LICENSE
/usr/share/doc/perl-Lingua-EN-Inflect-Number/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Lingua::EN::Inflect::Number.3
